version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "jimmy-todo-server"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1g81zuer98zm6"
s3_prefix = "jimmy-todo-server"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
